import React from "react";
import { MarkerType, Position } from "reactflow";

export const nodes = [
  {
    id: "1",
    type: "inputCustom",
    data: { label: "Input" },
    position: { x: 50, y: 150 },
  },
  {
    id: "2",
    type: "convNode",
    data: { label: "Conv1", parameters: { kernel_size: 3, stride: 1 } },
    position: { x: 250, y: 100 },
  },
  {
    id: "3",
    type: "convNode",
    data: { label: "Conv2", parameters: { kernel_size: 2, stride: 1 } },
    position: { x: 250, y: 200 },
  },
  {
    id: "4",
    type: "convNode",
    data: { label: "Conv3", parameters: { kernel_size: 5, stride: 1 } },
    position: { x: 250, y: 300 },
  },
  {
    id: "5",
    type: "convNode",
    data: { label: "Conv4", parameters: { kernel_size: 4, stride: 1 } },
    position: { x: 250, y: 400 },
  },
  {
    id: "6",
    type: "convNode",
    data: { label: "Conv5", parameters: { kernel_size: 2, stride: 1 } },
    position: { x: 250, y: 500 },
  },
  {
    id: "7",
    type: "Pool",
    data: { label: "Pool1", parameters: { pool_size: 2, stride: 2 } },
    position: { x: 450, y: 150 },
  },
  {
    id: "8",
    type: "Pool",
    data: { label: "Pool2", parameters: { pool_size: 2, stride: 2 } },
    position: { x: 450, y: 250 },
  },
  {
    id: "9",
    type: "Pool",
    data: { label: "Pool3", parameters: { pool_size: 2, stride: 2 } },
    position: { x: 450, y: 350 },
  },
  {
    id: "10",
    type: "FcNodes",
    data: { label: "FC1", parameters: { units: 64 } },
    position: { x: 650, y: 100 },
  },
  {
    id: "11",
    data: { label: "FC2", parameters: { units: 128 } },
    position: { x: 650, y: 200 },
  },
  {
    id: "12",
    type: "FcNodes",
    data: { label: "FC3", parameters: { units: 64 } },
    position: { x: 650, y: 300 },
  },
  {
    id: "13",
    type: "outputCustom",
    data: { label: "Output" },
    position: { x: 850, y: 150 },
  },
  {
    id: "14",
    type: "FcNodes",
    data: { label: "FC4", parameters: { units: 256 } },
    position: { x: 650, y: 400 },
  },
  {
    id: "15",
    type: "FcNodes",
    data: { label: "FC5", parameters: { units: 64 } },
    position: { x: 650, y: 500 },
  },
  {
    id: "16",
    type: "FcNodes",
    data: { label: "FC6", parameters: { units: 256 } },
    position: { x: 850, y: 250 },
  },
  {
    id: "17",
    type: "FcNodes",
    data: { label: "FC7", parameters: { units: 128 } },
    position: { x: 850, y: 350 },
  },
  {
    id: "18",
    type: "FcNodes",
    data: { label: "FC8", parameters: { units: 128 } },
    position: { x: 850, y: 450 },
  },
  {
    id: "19",
    type: "FcNodes",
    data: { label: "FC9", parameters: { units: 64 } },
    position: { x: 850, y: 550 },
  },
  {
    id: "20",
    type: "FcNodes",
    data: { label: "FC10", parameters: { units: 256 } },
    position: { x: 850, y: 650 },
  },
];

export const edges = [
  { id: "e1-2", source: "1", target: "2", animated: true },
  { id: "e1-3", source: "1", target: "3", animated: true },
  { id: "e1-4", source: "1", target: "4", animated: true },
  { id: "e1-5", source: "1", target: "5", animated: true },
  { id: "e1-6", source: "1", target: "6", animated: true },
  { id: "e2-7", source: "2", target: "7", animated: true },
  { id: "e2-8", source: "2", target: "8", animated: true },
  { id: "e2-9", source: "2", target: "9", animated: true },
  { id: "e3-10", source: "3", target: "10", animated: true },
  { id: "e3-11", source: "3", target: "11", animated: true },
  { id: "e3-12", source: "3", target: "12", animated: true },
  { id: "e4-13", source: "4", target: "13", animated: true },
  { id: "e5-14", source: "5", target: "14", animated: true },
  { id: "e5-15", source: "5", target: "15", animated: true },
  { id: "e6-16", source: "6", target: "16", animated: true },
  { id: "e6-17", source: "6", target: "17", animated: true },
  { id: "e6-18", source: "6", target: "18", animated: true },
  { id: "e6-19", source: "6", target: "19", animated: true },
  { id: "e6-20", source: "6", target: "20", animated: true },
  { id: "e7-13", source: "7", target: "13", animated: true },
  { id: "e8-13", source: "8", target: "13", animated: true },
  { id: "e9-13", source: "9", target: "13", animated: true },
  { id: "e10-13", source: "10", target: "13", animated: true },
  { id: "e11-13", source: "11", target: "13", animated: true },
  { id: "e12-13", source: "12", target: "13", animated: true },
  { id: "e14-13", source: "14", target: "13", animated: true },
  { id: "e15-13", source: "15", target: "13", animated: true },
  { id: "e16-13", source: "16", target: "13", animated: true },
  { id: "e17-13", source: "17", target: "13", animated: true },
  { id: "e18-13", source: "18", target: "13", animated: true },
  { id: "e19-13", source: "19", target: "13", animated: true },
  { id: "e20-13", source: "20", target: "13", animated: true },
];
